language: lisp
sudo: required

env:
  matrix:
    - LISP=sbcl

# either use a local install.sh script or install it via curl. Feel
# free to simplify this section in your own .travis.yml file.
install:
  - if [ -x ./install.sh ] && head -2 ./install.sh | grep '^# cl-travis' > /dev/null;
    then
      ./install.sh;
    else
      curl https://raw.githubusercontent.com/luismbo/cl-travis/master/install.sh | sh;
    fi

before_script:
  - openssl aes-256-cbc -k "$password" -in key-secret.lisp.enc -out key-secret.lisp -d
  - openssl aes-256-cbc -k "$password" -in nexmo1.key.enc -out nexmo1.key -d
  - sudo apt-get install npm
  - sudo npm install nexmo-cli -g
script:
  - cl -e '(ql:quickload :nexmo) (uiop:quit 0);success'
