(in-package :nexmo)
(defvar *server-callback* (db-unix::posix-getenv "NEXMO_CALLBACK"))
(defvar *key* (db-unix::posix-getenv "NEXMO_KEY"))
(defvar *secret* (db-unix::posix-getenv "NEXMO_SECRET"))
(defvar *app-id* (db-unix::posix-getenv "NEXMO_APP_ID"))
(defvar *key-file* (db-unix::posix-getenv "NEXMO_KEY_FILE"))
(defvar *handlers* (make-hash-table :test #'equal))
